/**
 * Post a triage template to the issue
 * @param {import('probot').Context} context
 */
export async function postTriageTemplate(context) {
  const { issue } = context.payload;
  
  const body = `@The-CS-Nerds/library-devs

A new issue has been marked for triage. Please review and complete the assessment below:

---

## 📋 Triage Assessment

### Quick Info
**Issue:** #${issue.number} - ${issue.title}  
**Author:** @${issue.user.login}  
**Created:** ${new Date(issue.created_at).toLocaleString()}

---

### Assessment Checklist

#### 🔍 Reproducibility
- [ ] **Reproducible** - Yes / No
- [ ] **Steps provided** - Clear / Needs clarification
- [ ] **Environment specified** - Yes / No

#### 🎯 Priority & Impact
**Priority:** [ ] p0 (Critical) / [ ] p1 (High) / [ ] p2 (Medium) / [ ] p3 (Low)

**Impact Assessment:**
- **Affected Users:** 
- **Severity:** 
- **Workaround Available:** Yes / No

**Suspected Cause:**
<!-- What do you think is causing this issue? -->


---

### 📝 Plan for Resolution

- [ ] **Step 1:** 
- [ ] **Step 2:** 
- [ ] **Step 3:** 

**Estimated Effort:** (Small / Medium / Large)

---

### 🔗 Additional Context

**Affected Files/Modules:**
<!-- List the files or modules that need changes -->


**Related Issues/PRs:**
<!-- Link any related issues or PRs -->


**Notes:**
<!-- Any other relevant information -->


---

### ✅ Triage Complete

Once triage is complete:
1. [ ] Apply appropriate priority label (p0-p3)
2. [ ] Add relevant component labels
3. [ ] Assign to a developer (if priority p0 or p1)
3. [ ] Remove "Triage Needed" label

<sub>This triage template was automatically generated by library-system-bot (built with Claude AI)</sub>`;

  await context.octokit.issues.createComment(
    context.issue({ body })
  );
}
